all:
	g++ -std=c++17 \
		-lreadline \
		-I build build/builtin-features.o build/core-shunting-yard.o \
		main.cpp -o main

static: 
	g++ -std=c++17 \
		-lreadline \
		-I build build/builtin-features.o build/core-shunting-yard.o \
		main.cpp -o main_static
